services:
  # Backend API Service
  - type: web
    name: fixit-now-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd fixit-now-backend && npm install && npm run migrate
    startCommand: cd fixit-now-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://fixit-now.onrender.com

  # Frontend Static Site
  - type: web
    name: fixit-now
    env: static
    buildCommand: cd fixit-now-frontend && npm install && npm run build
    staticPublishPath: fixit-now-frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://fixit-now-api.onrender.com
